# This is the main configuration file for Netlify.
# All build-related settings go under the [build] header.

[build]
  # 1. Install dependencies from the root package.json (for backend functions).
  # 2. Navigate into the frontend directory.
  # 3. Install frontend-specific dependencies.
  # 4. Build the frontend for production.
  command = "bun install && cd frontend && bun install && bun run build"
  
  # The location of the final, built website files.
  publish = "frontend/dist"
  
  # The location of our backend serverless functions.
  # This key MUST be inside the [build] block.
  functions = "backend/netlify/functions"

# --- Routing Rules ---

# This rule directs all API traffic to our backend function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# This rule is the catch-all for the React single-page app.
# It ensures direct navigation to pages like /login or /dashboard works.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200